import { expect, test } from '@playwright/test';
test('owner uses ledger, edits a fixture, asks assistant, and opens reminders', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: 'Open demo workspace' }).click();
  await expect(page.getByRole('heading', { name: 'Your ledger' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Edit', exact: true }).first()).toBeVisible();
  await page.screenshot({ path: 'test-results/ledger-desktop.png', fullPage: true });
  await page.getByRole('button', { name: '+ Add subscription', exact: true }).click();
  const name = 'Browser fixture ' + Date.now();
  await page.getByLabel('Subscription name', { exact: true }).fill(name);
  await page.getByLabel('Billing amount').fill('29.99');
  await page.getByLabel('End date', { exact: true }).fill('2040-01-01');
  await page.getByRole('button', { name: 'Create subscription', exact: true }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByPlaceholder('Search subscriptions or vendors…').fill(name);
  await page.getByRole('button', { name: 'Apply filters', exact: true }).click();
  await expect(page.getByRole('cell', { name: name }).first()).toBeVisible();
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  await page.getByRole('button', { name: 'Delete subscription', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm deletion', exact: true }).click();
  await expect(page.getByText('No subscriptions match these filters.')).toBeVisible();
  await page.getByRole('link', { name: 'Assistant', exact: false }).click();
  await page.getByRole('button', { name: 'How much do we spend? ↗', exact: true }).click();
  await expect(page.getByRole('link', { name: 'View matching subscriptions' })).toBeVisible();
  await page.getByRole('link', { name: 'View matching subscriptions' }).click();
  await expect(page.getByRole('heading', { name: 'Your ledger' })).toBeVisible();
  await page.getByRole('link', { name: 'Reminders', exact: false }).click();
  await expect(page.getByRole('heading', { name: 'Upcoming renewals' })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('link', { name: 'Ledger', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Your ledger' })).toBeVisible();
  await page.screenshot({ path: 'test-results/ledger-mobile.png', fullPage: true });
  expect(errors).toEqual([]);
});
