import { useEffect, useState } from 'react';
import { date, Identity, json, Ledger, Lookup, money, request, Row } from './api';
import { ItemEditor } from './ItemEditor';

const statuses = ['DRAFT', 'ACTIVE', 'PENDING_APPROVAL', 'TERMINATED'];
type Props = { query: string; token: string; user: Identity; owners: Lookup[]; vendors: Lookup[]; navigate: (path: string) => void };
export function LedgerView({ query, token, user, owners, vendors, navigate }: Props) {
  const initial = Object.fromEntries(new URLSearchParams(query));
  const [filters, setFilters] = useState<Record<string, string>>(initial); const [ledger, setLedger] = useState<Ledger>();
  const [cursor, setCursor] = useState<string>(); const [previous, setPrevious] = useState<Array<string | undefined>>([]);
  const [selected, setSelected] = useState<Set<string>>(new Set()); const [error, setError] = useState('');
  const [loading, setLoading] = useState(true); const [revision, setRevision] = useState(0); const [editor, setEditor] = useState<Row | 'new'>();
  const [bulkAction, setBulkAction] = useState('status'); const [bulkValue, setBulkValue] = useState('ACTIVE'); const [busy, setBusy] = useState(false);
  const params = new URLSearchParams(query); params.set('limit', '25'); if (cursor) params.set('cursor', cursor); else params.delete('cursor');
  useEffect(() => { let alive = true; setLoading(true); json<Ledger>('/line-items?' + params, token).then(result => { if (alive) { setLedger(result); setError(''); setSelected(new Set()); } }).catch(error => { if (alive) setError(error.message); }).finally(() => { if (alive) setLoading(false); }); return () => { alive = false; }; }, [query, cursor, revision, token]);
  function apply(next = filters) { const values = new URLSearchParams(); for (const [key, value] of Object.entries(next)) if (value && key !== 'cursor') values.set(key, value); navigate('/ledger?' + values); }
  function sort(field: string) { apply({ ...initial, sort: field, direction: initial.sort === field && initial.direction !== 'desc' ? 'desc' : 'asc' }); }
  function toggle(id: string) { setSelected(current => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }); }
  async function bulk() {
    setBusy(true); setError('');
    try { await json('/line-items/bulk', token, { method: 'POST', body: JSON.stringify({ action: bulkAction, actorId: user.ownerId,
      items: ledger!.items.filter(row => selected.has(row.id)).map(row => ({ id: row.id, expectedVersion: row.version })),
      ...(bulkAction === 'status' ? { status: bulkValue } : bulkAction === 'reassign' ? { ownerId: bulkValue } : {}),
    }) }); setRevision(value => value + 1); } catch (error) { setError((error as Error).message + ' Refresh the page before retrying a version conflict.'); } finally { setBusy(false); }
  }
  async function download() { try { const response = await request('/line-items/export?' + query, token); const url = URL.createObjectURL(await response.blob()); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'ledger.csv'; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch (error) { setError((error as Error).message); } }
  const a = ledger?.aggregates;
  const field = (name: string, label: string, type = 'text') => <label>{label}<input type={type} value={filters[name] || ''} onChange={event => setFilters({ ...filters, [name]: event.target.value })} step={type === 'number' ? '0.01' : undefined} min={type === 'number' ? '0' : undefined}/></label>;
  return <section className="page"><header className="page-heading"><div><span className="eyebrow">SUBSCRIPTION MANAGEMENT</span><h1>Your ledger</h1><p>Every subscription. A complete view of your spend.</p></div><div className="actions"><button onClick={download} className="secondary">↓ Export CSV</button><button className="primary" onClick={() => setEditor('new')}>+ Add subscription</button></div></header>
    <div className="metrics"><article><span>Listed billing amounts</span><strong>{a ? money(a.totalAmount) : '—'} <small>GEL</small></strong><p>Across the entire filtered set</p></article><article className="highlight"><span>Annualized recurring spend</span><strong>{a ? money(a.annualizedAmount) : '—'} <small>GEL / year</small></strong><p>Normalized to a common billing period</p></article><article><span>Matching subscriptions</span><strong>{a?.matchingCount ?? '—'}<small> records</small></strong><p>Soft-deleted items excluded</p></article></div>
    <div className="panel"><div className="panel-heading"><h2>All subscriptions <span className="count">{a?.matchingCount ?? '…'}</span></h2><button className="text-button" onClick={() => setRevision(value => value + 1)}>↻ Refresh</button></div>
      <form className="filters" onSubmit={event => { event.preventDefault(); apply(); }}>
        <label className="search-field">Search<input placeholder="Search subscriptions or vendors…" value={filters.search || ''} onChange={event => setFilters({ ...filters, search: event.target.value })}/></label>
        <label>Vendor<select value={filters.vendorId || ''} onChange={event => setFilters({ ...filters, vendorId: event.target.value })}><option value="">All vendors</option>{vendors.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label>
        <label>Status<select value={filters.status || ''} onChange={event => setFilters({ ...filters, status: event.target.value })}><option value="">All statuses</option>{statuses.map(s => <option key={s}>{s}</option>)}</select></label>
        <details className="more-filters"><summary>More filters</summary><div className="filter-popover">{field('category', 'Category')}{user.role === 'admin' && <label>Owner<select value={filters.ownerId || ''} onChange={event => setFilters({ ...filters, ownerId: event.target.value })}><option value="">All owners</option>{owners.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}{field('minAmount', 'Minimum amount', 'number')}{field('maxAmount', 'Maximum amount', 'number')}{field('renewalFrom', 'Renewal from', 'date')}{field('renewalTo', 'Renewal to', 'date')}</div></details>
        <button className="secondary">Apply filters</button>{query && <button type="button" className="text-button" onClick={() => navigate('/ledger')}>Clear</button>}
      </form>
      {error && <div role="alert" className="error">{error}</div>}
      {!!selected.size && <div className="bulk-bar"><strong>{selected.size} selected</strong><select aria-label="Bulk action" value={bulkAction} onChange={event => { setBulkAction(event.target.value); setBulkValue(event.target.value === 'status' ? 'ACTIVE' : owners[0]?.id || ''); }}><option value="status">Change status</option>{user.role === 'admin' && <option value="reassign">Reassign owner</option>}<option value="delete">Delete selected</option></select>{bulkAction !== 'delete' && <select aria-label="Bulk value" value={bulkValue} onChange={event => setBulkValue(event.target.value)}>{bulkAction === 'status' ? statuses.map(s => <option key={s}>{s}</option>) : owners.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select>}<button disabled={busy} className={bulkAction === 'delete' ? 'danger' : 'primary'} onClick={bulk}>{busy ? 'Applying…' : bulkAction === 'delete' ? 'Confirm deletion' : 'Apply to selected'}</button><button className="text-button" onClick={() => setSelected(new Set())}>Cancel</button></div>}
      <div className="table-scroll" aria-busy={loading}><table><thead><tr><th><input aria-label="Select all on page" type="checkbox" checked={!!ledger?.items.length && selected.size === ledger.items.length} onChange={event => setSelected(new Set(event.target.checked ? ledger?.items.map(row => row.id) : []))}/></th><th><button onClick={() => sort('vendor')}>Subscription / vendor ↕</button></th><th><button onClick={() => sort('category')}>Category ↕</button></th><th><button onClick={() => sort('status')}>Status ↕</button></th><th className="numeric"><button onClick={() => sort('amount')}>Amount ↕</button></th><th><button onClick={() => sort('renewalDate')}>Renewal ↕</button></th><th><button onClick={() => sort('startDate')}>Start date ↕</button></th><th/></tr></thead><tbody>{ledger?.items.map(row => <tr key={row.id}><td><input aria-label={'Select ' + row.name} type="checkbox" checked={selected.has(row.id)} onChange={() => toggle(row.id)}/></td><td><div className="vendor-cell"><div className="vendor-mark">{row.vendorName.slice(0, 1)}</div><div><strong>{row.name}</strong><small>{row.vendorName}</small></div></div></td><td><span className="category">{row.category}</span></td><td><span className={'status ' + row.status.toLowerCase()}>{row.status.toLowerCase().replaceAll('_', ' ')}</span></td><td className="numeric"><strong>{money(row.amount)}</strong><small>GEL · {row.billingPeriod.toLowerCase()}</small></td><td>{date(row.renewalDate)}</td><td>{date(row.startDate)}</td><td><button className="text-button" onClick={() => setEditor(row)}>Edit</button></td></tr>)}</tbody></table>{loading && <div className="table-state" role="status">Loading subscriptions…</div>}{!loading && !ledger?.items.length && <div className="table-state">No subscriptions match these filters.</div>}</div>
      <footer className="pagination"><span>Page {previous.length + 1} · {ledger?.items.length ?? 0} shown</span><div className="actions"><button className="secondary" disabled={!previous.length || loading} onClick={() => { setCursor(previous.at(-1)); setPrevious(previous.slice(0, -1)); }}>← Previous</button><button className="secondary" disabled={!ledger?.nextCursor || loading} onClick={() => { setPrevious([...previous, cursor]); setCursor(ledger!.nextCursor!); }}>Next →</button></div></footer>
    </div>
    <div className="breakdowns">{[['By category', a?.byCategory], ['Top vendors', a?.byVendor]] .map(([title, groups]) => <article className="panel" key={String(title)}><h2>{String(title)}</h2>{(groups as Ledger['aggregates']['byVendor'] | undefined)?.slice(0, 5).map((group, i) => <div className="breakdown" key={i}><span>{group.category || group.vendorName}</span><strong>{money(group.totalAmount)} <small>GEL</small></strong></div>)}</article>)}</div>
    {editor && <ItemEditor row={editor === 'new' ? undefined : editor} token={token} user={user} vendors={vendors} owners={owners} onClose={() => setEditor(undefined)} onSaved={() => { setEditor(undefined); setRevision(value => value + 1); }}/>} 
  </section>;
}
